### ISSUE TITLE
프로그램 실행 시, Traceback (오류 메시지) 도 안나오고 꺼짐

### ISSUE THREAD

**Issue by dh22659** [monkm1/onadaily#1]
프로그램 실행하면, 5초간 대기하다가, 오류메시지가 잔뜩 나오는데, 오류메시지 나오자마자 프로그램이 종료됩니다.
그래서 어떤 오류인지 알아볼 수가 없어서 이렇게 적습니다.

이 현상이 나타난 지는 3일 정도 됐습니다.

**Comment by monkm1** [comment]
@dh22659 댓글만 보고 이슈를 못봐서 이걸 지금에서야 봤네요
혹시 아직도 같은 상황이신가요?

**Comment by dh22659** [comment]
어제(8/22) 까지는 1.27 ver을 설치해서 사용하니까 문제 없었는데, 오늘 크롬 업데이트 이후로 다시 같은 문제가 발생했어요.
그래서 답글 남깁니다. 
우선 저도 최신 릴리즈 버전으로 시도해보고 오겠습니다
