### ISSUE TITLE
바나나몰 에러

### ISSUE THREAD

**Issue by IlovePC21** [monkm1/onadaily#3]
감사하게 잘 쓰고 있습니다! 바나나몰이 며칠전부터 안되네요. 크롬 버전은 126 입니다.
소셜 로그인은 사용하지 않고 있으며 headless false true는 상관없이 안되네요.
------------
크롬 에러가 발생했습니다. 소셜 로그인을 사용하면 열려있는 크롬 창을 전부 닫고 실행해 주세요.
Traceback (most recent call last):
  File "onadaily.py", line 145, in run
  File "onadaily.py", line 59, in check
  File "onadaily.py", line 84, in login
  File "webdriverwrapper.py", line 56, in wait_move_click
  File "webdriverwrapper.py", line 52, in move_to
  File "selenium\webdriver\common\action_chains.py", line 103, in perform
  File "selenium\webdriver\common\actions\action_builder.py", line 96, in perform
  File "selenium\webdriver\remote\webdriver.py", line 345, in execute
  File "selenium\webdriver\remote\errorhandler.py", line 229, in check_response
selenium.common.exceptions.JavascriptException: Message: javascript error: {"status":60,"value":"[object HTMLInputElement] has no size and location"}
  (Session info: chrome=126.0.6478.127)
Stacktrace:
        GetHandleVerifier [0x00007FF61B21EEA2+31554]
        (No symbol) [0x00007FF61B197ED9]
        (No symbol) [0x00007FF61B05872A]
        (No symbol) [0x00007FF61B05E55E]
        (No symbol) [0x00007FF61B060EB1]
        (No symbol) [0x00007FF61B060F50]
        (No symbol) [0x00007FF61B0AF513]
        (No symbol) [0x00007FF61B0AE776]
        (No symbol) [0x00007FF61B0F6D74]
        (No symbol) [0x00007FF61B0CD02A]
        (No symbol) [0x00007FF61B0EC977]
        (No symbol) [0x00007FF61B0CCDD3]
        (No symbol) [0x00007FF61B09A33B]
        (No symbol) [0x00007FF61B09AED1]
        GetHandleVerifier [0x00007FF61B528B1D+3217341]
        GetHandleVerifier [0x00007FF61B575AE3+3532675]
        GetHandleVerifier [0x00007FF61B56B0E0+3489152]
        GetHandleVerifier [0x00007FF61B2CE776+750614]
        (No symbol) [0x00007FF61B1A375F]
        (No symbol) [0x00007FF61B19EB14]
        (No symbol) [0x00007FF61B19ECA2]
        (No symbol) [0x00007FF61B18E16F]
        BaseThreadInitThunk [0x00007FF887C9257D+29]
        RtlUserThreadStart [0x00007FF88894AF28+40]

DevTools listening on ws://127.0.0.1:64913/devtools/browser/e283c5d2-4519-474f-92c3-a15c032fb021

**Comment by monkm1** [comment]
1.3.0pre5에서 fix됨
지속되면 코멘트 주세요.

**Comment by IlovePC21** [comment]
1.3.0pre5 에서 잘 되네요!
