### ISSUE TITLE
1.2.10 버전 사용중. 며칠전부터 바나나몰과 오나미몰만 로그인 실패.

### ISSUE THREAD

**Issue by dh22659** [monkm1/onadaily#4]
구글 연동로그인 사용중이구요.

한 4일전부터 바나나몰, 오나미몰만 로그인 실패합니다.

**Comment by monkm1** [comment]
[프리뷰 버전](https://github.com/monkm1/onadaily/releases/tag/v1.3.0pre5)(1.3.0pre5)을 사용해 보세요.
